# Generated by Django 4.1 on 2022-11-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_remove_borrowing_check_actual_return_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_actual_return_date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("actual_return_date__isnull", True),
                        ("actual_return_date__gte", models.F("borrow_date")),
                        _connector="OR",
                    )
                ),
                name="check_actual_return_date",
            ),
        ),
    ]
