# Generated by Django 4.1 on 2022-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63)),
                ("author", models.CharField(max_length=63)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hard"), ("SOFT", "Soft")], max_length=4
                    ),
                ),
                ("inventory", models.PositiveIntegerField(default=0)),
                (
                    "monthly_annual_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Monthly annual fee in $USD",
                    ),
                ),
            ],
        ),
    ]
